name: Snapcast Multi-Output
slug: snapcast-multiout
version: "0.31.0-6"
description: Snapserver + dynamic Snapclients for multi-output USB audio with Music Assistant
url: https://github.com/damianflynn/snapcast-multiout
arch: [amd64, aarch64]
startup: services
boot: auto
host_network: true
privileged: true
audio: true
devices:
  - /dev/snd
udev: true
map:
  - share:rw
options:
  list_devices_on_start: true
  streams:
    # EDIT these in the add-on UI. For first test, keep 1–2 streams on your Sound Blaster.
    - name: kitchen
      device: default
    - name: sitting_room
      device: default
schema:
  list_devices_on_start: bool
  streams:
    - name: str
      device: str
