name: Snapcast Multi-Output
slug: snapcast-multiout
version: "0.31.0-25"
description: Snapserver + dynamic Snapclients for multi-output USB audio with Music Assistant
url: https://github.com/damianflynn/snapcast-multiout
arch: [amd64, aarch64]
startup: services
boot: auto
host_network: true
audio: true
devices:
  - /dev/snd
udev: true
map:
  - share:rw
webui: http://[HOST]:[PORT:1780]
options:
  list_devices_on_start: true
  streams:
    - name: kitchen
      device: default
    - name: sitting_room
      device: default
schema:
  list_devices_on_start: bool
  streams:
    - name: str
      device: str
