name: Snapcast Multi-Output
slug: snapcast-multiout
version: "0.31.0-5"
description: Snapserver + dynamic Snapclients for multi-output USB (UMC1820) with Music Assistant
url: https://github.com/damianflynn/snapcast-multiout
arch: [amd64, aarch64]
startup: services
boot: auto
host_network: true
init: false
privileged: true
audio: true
map:
  - share:rw
devices:
  - /dev/snd
  - /dev/dri
udev: true
options:
  list_devices_on_start: true
  streams:
    # EDIT these in the add-on UI. For first test, keep 1–2 streams on your Sound Blaster.
    - name: kitchen
      device: default
    - name: sitting_room
      device: default
schema:
  list_devices_on_start: bool
  streams:
    - name: str
      device: str
