name: Snapcast Multi-Output
slug: snapcast-multiout
version: "2025.09.23-3"
description: Snapserver + dynamic Snapclients for multi-output USB audio with Music Assistant
url: https://github.com/damianflynn/snapcast-multiout
arch: [amd64, aarch64]
image: "ghcr.io/damianflynn/snapcast-multiout"
startup: services
boot: auto
host_network: true
audio: true
devices:
  - /dev/snd
udev: true
map:
  - share:rw
ingress: true
ingress_port: 1780
panel_icon: mdi:speaker-multiple
options:
  list_devices_on_start: true
  streams:
    - name: kitchen
      device: default
    - name: sitting_room
      device: default
schema:
  list_devices_on_start: bool
  streams:
    - name: str
      device: str
